# TODO: Set up the initial config file using ansible config options (mainly paths | Remember to update the ansible
#       config files respectively)

---
- name: Deploy the latest version of the scripts to the CRT-connected raspberry pi
  hosts: crt
  roles:
    - name: samba
    - name: uv
    - name: imagemagick
    - name: crt-tv
    - name: kodi-autoexec
