---
- name: Deploy the latest version of the scripts to the CRT-connected raspberry pi
  hosts: crt
  roles:
    - name: rgbpi
    - name: samba
    - name: uv
    - name: imagemagick
    - name: crt-tv
    - name: kodi-autoexec
    - name: kodi-keymaps
