---
- name: Install system packages requirements
  ansible.builtin.apt:
    state: present
    name:
      - tesseract-ocr
      - tesseract-ocr-eng
      - imagemagick
      - ffmpeg
      - git

- name: Fetch the latest version of the repo from GitHub
  ansible.builtin.git:
    repo: 'https://github.com/arturbalabanov/crt-tv'
    dest: "{{ install_dir }}"
    version: "{{ version }}"
  register: result
  changed_when: result.before != result.after

- name: Install the CLI tool
  ansible.builtin.command:
    cmd: uv tool install . --editable --reinstall
    chdir: "{{ install_dir }}"
  when: result.before != result.after
  changed_when: true

- name: Deploy crt_tv_fs_observer.service systemd service
  ansible.builtin.template:
    src: templates/crt_tv_fs_observer.service.jinja2
    dest: /etc/systemd/system/crt_tv_fs_observer.service
    group: root
    owner: root
    mode: 0644

- name: Enable and restart crt_tv_fs_observer.service
  ansible.builtin.systemd_service:
    enabled: true
    daemon_reload: true
    state: restarted
    name: crt_tv_fs_observer.service
